---
title: "R Workbook 5"
output: html_notebook
---
Author: Avik Deb (avikdeb@gmail.com)

14 November, 2018

<br>

### Day 5

<br>

#### Fundamentals of Statistics #1

<br>

<b>Measures of Central Tendency - </b> Following are covered here:

*Mean*
*Median*
*Mode* 

R has built-in functions to perform above operations. The missing value is handled in the argument.

```{r}

# Calculating means

x<-c(10, 2, 30, 4, 5, 6, 70, 8, 9, 10)
y<-c(1,2,3,4,5,NA)

# Mean of x
mean(x)

# Mean of x with trim - used to drop some observations from both end of the sorted vector - 0.2 means remove 2 elements from both ends
mean(x, trim = 0.2)

# Mean of y - removing the missing values
mean(y, na.rm = TRUE)

cat("-----------------------------","\n")
# Calculating median

x<-c(10, 2, 30, 2, 5, 8, 70, 8, 9, 2)
y<-c(3,2,3,4,5,NA)

median(x)
median(y, na.rm = TRUE)

cat("-----------------------------","\n")



```

<br>
<b>Dispersion - </b> Following are covered here:

*Variance*
*Standard Deviation*

```{r}

student.data <- read.csv("student.csv")

print(student.data)

# Getting the highest score i.e. a specific data
highest.score <- max(student.data$total_score)
print(highest.score)

# Getting the full record of highest score
ret.val <- subset(student.data, total_score == max(total_score))
print(ret.val)

# Getting the best attendance in class 5
best.attend.5 <- subset(student.data, days_absent == min(days_absent) & class == 5)
best.attend.5

```