---
title: "R Workbook 3"
output: html_notebook
---
Author: Avik Deb (avikdeb@gmail.com)

10 November, 2018

<br>

### Day 3

<br>

#### Graphics - Visualize Data

<br>

<b>1. Bar Charts - </b> Use function **barplot()**

```{r}

max.temp <- c(22, 24, 25, 25, 26, 24, 27)
# min.temp <- c(18, 18, 19, 18, 20, 22, 23)

# Below is just basic - keep it commented once understood - we will use the detail one
# barplot(max.temp)

# Below is the detail one - use it and keep this as uncommented
barplot(max.temp, main = "Max Temperature Variation Over a Week", xlab = "Days", ylab = "Max Temperature", names.arg = c("Mon", "Tue", "Wed", "Thu","Fri", "Sat", "Sun"), col = "#CEE95F", border = "red")

# Provide a name to the chart and save the file as image
#png("temp_chart.png")


```
<br>

<b>TBD - </b> Missing values are denoted by NA or NaN for undefined mathematical operations. Below functions are used to test such scenarios:



```{r}

# Test the missing value



```


<b>TBD - </b>Used to store tabular data in R. Package dplyr is very useful while working with data frames. Data frames are 


```{r}



```

